### ISSUE TITLE
Errore nella pagina del Carrello con utente autenticato (admin) e carrello vuoto

### ISSUE THREAD

**Issue by killbizz** [OmicronSwe/EmporioLambda-FE#23]
To reproduce:

- utente admin autenticato
- carrello vuoto
- premere Pay button

Result: 

Unhandled Runtime Error
TypeError: stripe is null
components\Cart\PayButtonContent.tsx (28:4)

**Comment by matthew-balzan** [comment]
Fixed in fix&testCart
